### ISSUE TITLE
From markers detection to mesh

### ISSUE THREAD

**Issue by JPFrancoia** [pinae/Zozo-Measurer#2]
hello,

I recently learned that zozo is going to close soon (at least in Europe), and I was looking for a way to still use the suit. This page: https://erwin.ried.cl/post/178913171442/how-precise-is-the-zozosuit describes how to get a mesh from the json we can download on zozo's website.

Your library allows to detect the markers on a picture. With several pictures, would it be possible to use your code to reconstruct a mesh ?

Best

**Comment by pinae** [comment]
I guess it would be possible. If you try it out I wold be delighted if you let me know how well it works.

**Comment by eried** [comment]
I would be happy to know too 😄 I was tracking my gym changes and zozo ceased operations... http://vm.tiktok.com/aykumj/

No idea why they don't open sourced the technology

**Comment by pinae** [comment]
It is a pity indeed.

Please reopen the issue if there is something new for creating a mesh.
